### ISSUE TITLE
9 - 11

### ISSUE THREAD

**Issue by DylanMoriarty** [DylanMoriarty/Tomorrow#2]
## Tasks
- [ ] Finish On-Boarding
- [ ] Meet with Nick
- [ ] WorldPop 

## Places to be
- [ ] 10am - Coffee with Schuler
- [ ] 11am - Eggrolls
